name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
      - name: Checkout Repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --ignore-scripts

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        # https://github.com/changesets/action
        uses: changesets/action@v1
        with:
          createGithubReleases: false
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: View outputs
        run: echo ${{join(steps.changesets.outputs.*, ' ')}}

      - name: Aggregate
        id: aggregate
        if: steps.changesets.outputs.published == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          node ./.changeset/aggregate.mjs

      - name: Create Release
        if: steps.changesets.outputs.published == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.aggregate.outputs.version }}
          release_name: ${{ steps.aggregate.outputs.version }}
          body: ${{ steps.aggregate.outputs.notes }}
          draft: false
          prerelease: false
